print('Escape\tSequences\n'
      '\\\'\t\tSingle Quote\n'
      '\\\t\tBackslash\n'
      '\\n\t\tNew Line\n'
      '\\r\t\tCarriage Return\n'
      '\\t\t\tTab\n'
      '\\b\t\tBackspace\n'
      '\\f\t\tForm Feed\n'
      '\\a\t\tBell(alert)\n'
      '\\\'\t\tSingle Quotation mark\n'
      '\\\"\t\tDouble Quotation mark\n'
      '\\ooo\tOctal value\n'
      '\\xhh\tHex value')
